keys:
  - &vps age16wt580y8f03zujn68wqsyf64ajw72pmx7j703dwfu8mk4lfwwqfsyf9g7w
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *vps
  - path_regex: mx-proxy-secrets\.yaml$
    key_groups:
      - age:
          - *vps
